name: Dockerfile Linting

on:
  push:
    paths:
      - 'Dockerfile'
  pull_request:
    paths:
      - 'Dockerfile'

jobs:
  hadolint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run Hadolint
      uses: hadolint/hadolint-action@v1.5.0
      with:
        dockerfile: './Dockerfile'
