name: Dockerfile Linting

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  hadolint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run Hadolint
      uses: hadolint/hadolint-action@v1.5.0
      with:
        dockerfile: './Dockerfile'
