name: OWASP Dependency Check

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Install dependencies
      run: dotnet restore

    - name: OWASP Dependency Check
      uses: ShiftLeftSecurity/dependency-check-action@main
      with:
        path: './'
        format: 'html'
        failBuild: true
        failBuildOnCVSS: 7
