name: Snyk Security Scan

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t programming-c-sharp -f Dockerfile .

    - name: Install Snyk
      run: npm install -g snyk

    - name: Run Snyk to check for vulnerabilities
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk test --docker programming-c-sharp --file=Dockerfile
