name: Snyk Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t programming-c-sharp -f Dockerfile .

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Snyk
      run: npm install -g snyk

    - name: Run Snyk to check for vulnerabilities
      run: snyk test --token ${{ secrets.SNYK_TOKEN }}
